FROM cgr.dev/chainguard/python:latest-dev AS buildando

WORKDIR /app

COPY requirements.txt .

RUN pip install --user --no-cache-dir -r requirements.txt

FROM cgr.dev/chainguard/python:latest

WORKDIR /app

COPY --from=buildando /home/nonroot/.local /home/nonroot/.local

COPY app.py .
COPY templates templates/
COPY static static/

ENV PATH="/home/nonroot/.local/bin:$PATH"
ENV FLASK_APP=app.py

ENTRYPOINT ["python", "-m", "flask", "run", "--host=0.0.0.0"]
